default:
  layer: 2
  alias: resources/alias/default.exo
ゆかり:
  layer: 10
  alias: resources/alias/yukari.exo
  voice: ゆかり
あかり:
  layer: 14
  alias: resources/alias/akari.exo
  voice: あかり
slide:
  layer: 2
  alias: resources/alias/slide_template.exo
