default:
  layer: 2
  alias: resources/alias/default.exo
  voice: ゆかり
雫:
  layer: 5
  alias: resources/alias/yukari.exo
  voice: 雫
ゆかり:
  layer: 10
  alias: resources/alias/yukari.exo
  voice: ゆかり
あかり:
  layer: 14
  alias: resources/alias/akari.exo
  voice: あかり
slide:
  layer: 2
  alias: resources/alias/slide_template.exo
茜:
  layer: 3
  alias: resources/alias/yukari.exo
  voice: 茜
葵:
  layer: 9
  alias: resources/alias/yukari.exo
  voice: 葵
